### ISSUE TITLE
program crashes on Windows when trying to parse default settings json

### ISSUE THREAD

**Issue by durandarthur** [lee-b/kobold_assistant#15]
https://github.com/lee-b/kobold_assistant/blob/2add917b6d3f31764bd2e9d97a9cd8c6ef841aef/src/kobold_assistant/default_settings.json#L82C7-L82C10

The emojis in the file above cause the parser to error because Python uses CP-1252 encoding by default, on Windows.

I've already found the answer, so you can close the issue:

Windows users need to make and set the PYTHONUTF8 environment variable to the value 1
Or alternatively, use the command line option -Xutf8.

**Comment by lee-b** [comment]
Windows is not supported, but patches to properly port it to Windows are welcome.
