### ISSUE TITLE
Dependencies list 

### ISSUE THREAD

**Issue by Zipties** [lee-b/kobold_assistant#4]
I had to install the following packages from _main_.py. I'd add them to the readme, but I haven't worked with GitHub before and don't want to mess anything up for you. 

pip install --upgrade pip
pip install librosa==0.10.0.* bnunicodenormalizer==0.1.1
pip install gruut pyaudio speechrecognition torch torchaudio TTS pydub

**Comment by lee-b** [comment]
Hi.  Did you install from the .whl file?  It should have installed these as requirements for you.  As you can see, gruut (for example) is specified in the pyproject.toml file, that the whl is built from.

**Comment by lee-b** [comment]
Closing as there's no feedback, and this was likely a misunderstanding, looking for traditional requirements.txt or setup.py when poetry is used.
