### ISSUE TITLE
Installation - Ubuntu 22.04 - Where is the .whl file?

### ISSUE THREAD

**Issue by kdwoell** [lee-b/kobold_assistant#7]
Hello, great project and look forward to trying out KA (Kobold-Assisant).
Below excerpt from the Install guidance:
Download the *.whl file from the latest release on github 
Run pip install *.whl.

I did a git clone of the repo, and searched thoroughly but cannot find a .whl file. 
Am I mission something?

**Comment by lee-b** [comment]
Hi, go to https://github.com/lee-b/kobold_assistant/releases and then expand Assets under the most recent release.  Sorry it's not more obvious, that's just how github works.
